
# Analysis Parameters
parameters:
  surface_metal_z_percentile: 98.0
  pbc_analysis: [true, true, false]
  bond_hysteresis: 0.15  
  # Elements
  adsorbate_elements: ["C", "H", "O"] 
  lattice_elements: ["O"] 
  # Z-Height Tolerances & Depths (in Å)
  lattice_z_tolerance: 0.7  # How far above the surface Z a lattice atom can be
  adsorbate_depth: 0.5      # How far below the surface Z an adsorbate can dip
  metal_depth: 2.0          # How deep to track subsurface metals
  lattice_depth: 2.0        # How deep to track subsurface lattice atoms

# Bond Cutoffs in Å (Sorted alphabetically for consistency)
cutoffs:
  "C-C": 1.64
  "C-H": 1.19
  "C-M": 2.20
  "C-O": 1.53
  "H-H": 0.84
  "H-M": 1.80
  "H-O": 1.08
  "M-O": 2.10
  "O-O": 1.58

# Species Map: [C, H, O] -> Name
species:
  "1,4,0": "CH4"
  "1,3,0": "CH3"
  "0,0,2": "O2"
  "0,2,1": "H2O"
  "1,0,1": "CO"
  "1,0,2": "CO2"
  "0,2,0": "H2"
  "0,1,1": "OH"
  "1,2,1": "CH2O"
  "1,3,1": "CH3O"
  "1,1,1": "HCO"
  "0,0,1": "O"
  "0,1,0": "H"
  "2,4,0": "C2H4"
  "2,6,0": "C2H6"
  "2,4,1": "C2H4O"
  "2,3,1": "C2H3O"
  "1,1,0": "CH"
  "1,2,0": "CH2"